version: 2

before:
  hooks:
    - go install github.com/Songmu/gocredits/cmd/gocredits@latest
    - gocredits -w .
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/abicky/ecsmec/cmd.revision={{.ShortCommit}}
archives:
  - # Exclude the version from the default name_template to download the latest version via https://github.com/abicky/ecsmec/releases/latest/download/$archive_name
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    files:
      - LICENSE
      - README.md
      - CREDITS
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
brews:
  - repository:
      owner: abicky
      name: homebrew-tools
    homepage: "https://github.com/abicky/ecsmec"
    description: "A CLI tool for Amazon ECS that provides some commands to execute bothersome operations"
    directory: Formula
    test: |
      system "#{bin}/ecsmec --version"
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
