name: main
on:
  push:
  pull_request:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --snapshot --verbose
        env:
          # Use a custom token instead of GITHUB_TOKEN for the homebrew tap
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
