name: main
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go install go.uber.org/mock/mockgen@latest

      # `go test` uses only a high-confidence subset of go vet, so execute also `go vet`
      - run: make vet

      - run: go fmt ./... && git diff --exit-code -- ':!go.sum'

      - run: make test

  release:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Check the version
        run: grep -qr "version = \"$(git tag --points-at HEAD | sed 's/^v//')\"" cmd

      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          # Use a custom token instead of GITHUB_TOKEN for the homebrew tap
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
