name: main
on:
  push:
  pull_request:

env:
  GO_VERSION: 1.22

jobs:
  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # `go test` uses only a high-confidence subset of go vet, so execute also `go vet`
      - run: go vet ./...

      - run: go fmt ./... && git diff --exit-code -- ':!go.sum'

      - run: make test

  release:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'tags/v')
    steps:
      - uses: actions/checkout@v2

      - name: Check the version
        run: grep -qr "version = \"$(git tag --points-at HEAD | sed 's/^v//')\"" cmd

      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          # Use a custom token instead of GITHUB_TOKEN for the homebrew tap
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
